version: "3.1"
services:

  db:
    image: postgres
    container_name: example-postgres
    restart: always
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/database/postgres
    ports:
      - 5432:5432

volumes:
  database-data:

